//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChangeTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.Views.ChangeTime", typeof(ChangeTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time.
        /// </summary>
        public static string Add_time {
            get {
                return ResourceManager.GetString("Add_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the times only for the active participants in the online contest. Does not affect the total duration of the contest nor its start or end time..
        /// </summary>
        public static string Change_time_legend {
            get {
                return ResourceManager.GetString("Change_time_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;-Negative number Subtracts&lt;/strong&gt; time..
        /// </summary>
        public static string Negative_number_legend {
            get {
                return ResourceManager.GetString("Negative_number_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Time for active participants.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;+Positive number Adds&lt;/strong&gt; time..
        /// </summary>
        public static string Positive_number_legend {
            get {
                return ResourceManager.GetString("Positive_number_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Time.
        /// </summary>
        public static string Subtract_time {
            get {
                return ResourceManager.GetString("Subtract_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in minutes.
        /// </summary>
        public static string Time_in_minutes {
            get {
                return ResourceManager.GetString("Time_in_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is required, please add a value different from 0.
        /// </summary>
        public static string Time_required_error {
            get {
                return ResourceManager.GetString("Time_required_error", resourceCulture);
            }
        }
    }
}
