//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Submissions.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionAdministration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionAdministration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Submissions.ViewModels.Submissio" +
                            "nAdministration", typeof(SubmissionAdministration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content_as_string {
            get {
                return ResourceManager.GetString("Content_as_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required.
        /// </summary>
        public static string Content_required {
            get {
                return ResourceManager.GetString("Content_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File submission.
        /// </summary>
        public static string File_submission {
            get {
                return ResourceManager.GetString("File_submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The participant is required!.
        /// </summary>
        public static string Participant_required {
            get {
                return ResourceManager.GetString("Participant_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem is required!.
        /// </summary>
        public static string Problem_required {
            get {
                return ResourceManager.GetString("Problem_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is required!.
        /// </summary>
        public static string Type_required {
            get {
                return ResourceManager.GetString("Type_required", resourceCulture);
            }
        }
    }
}
