//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionsView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionsView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.Views.Submissions.SubmissionsView", typeof(SubmissionsView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string Answer_correct {
            get {
                return ResourceManager.GetString("Answer_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect answer.
        /// </summary>
        public static string Answer_incorrect {
            get {
                return ResourceManager.GetString("Answer_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s profile.
        /// </summary>
        public static string Authors_profile {
            get {
                return ResourceManager.GetString("Authors_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation result.
        /// </summary>
        public static string Compilation_result {
            get {
                return ResourceManager.GetString("Compilation_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compile time error occurred..
        /// </summary>
        public static string Compile_time_error_occured {
            get {
                return ResourceManager.GetString("Compile_time_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled successfully..
        /// </summary>
        public static string Compiled_successfully {
            get {
                return ResourceManager.GetString("Compiled_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download binary file.
        /// </summary>
        public static string Download_binary_file {
            get {
                return ResourceManager.GetString("Download_binary_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution result.
        /// </summary>
        public static string Execution_result {
            get {
                return ResourceManager.GetString("Execution_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected output:.
        /// </summary>
        public static string Expected_output {
            get {
                return ResourceManager.GetString("Expected_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide input.
        /// </summary>
        public static string Hide_input_text {
            get {
                return ResourceManager.GetString("Hide_input_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory limit.
        /// </summary>
        public static string Memory_limit {
            get {
                return ResourceManager.GetString("Memory_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory used.
        /// </summary>
        public static string Memory_used {
            get {
                return ResourceManager.GetString("Memory_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest.
        /// </summary>
        public static string Retest {
            get {
                return ResourceManager.GetString("Retest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run #.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error.
        /// </summary>
        public static string Runtime_error {
            get {
                return ResourceManager.GetString("Runtime_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show input.
        /// </summary>
        public static string Show_input_text {
            get {
                return ResourceManager.GetString("Show_input_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string Source_code {
            get {
                return ResourceManager.GetString("Source_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission is in queue and will be processed shortly. Please wait..
        /// </summary>
        public static string Submission_in_queue {
            get {
                return ResourceManager.GetString("Submission_in_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission is deleted!!!.
        /// </summary>
        public static string Submission_is_deleted {
            get {
                return ResourceManager.GetString("Submission_is_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission is being processed at the moment... Please wait..
        /// </summary>
        public static string Submission_is_processing {
            get {
                return ResourceManager.GetString("Submission_is_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string Submissions {
            get {
                return ResourceManager.GetString("Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test #.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test input:.
        /// </summary>
        public static string Test_input {
            get {
                return ResourceManager.GetString("Test_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit.
        /// </summary>
        public static string Time_limit {
            get {
                return ResourceManager.GetString("Time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time used.
        /// </summary>
        public static string Time_used {
            get {
                return ResourceManager.GetString("Time_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution #{0} by {1} for problem {2}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus, turpis quis consequat mattis, erat ex iaculis dui, ut porttitor orci tellus quis erat.
        /// </summary>
        public static string User_retest_prompt {
            get {
                return ResourceManager.GetString("User_retest_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View code.
        /// </summary>
        public static string View_code {
            get {
                return ResourceManager.GetString("View_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your output:.
        /// </summary>
        public static string Your_output {
            get {
                return ResourceManager.GetString("Your_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero test #.
        /// </summary>
        public static string Zero_test {
            get {
                return ResourceManager.GetString("Zero_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero tests are not included in the final result..
        /// </summary>
        public static string Zero_tests_not_included_in_result {
            get {
                return ResourceManager.GetString("Zero_tests_not_included_in_result", resourceCulture);
            }
        }
    }
}
