//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Submissions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionsControllers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionsControllers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Submissions.SubmissionsControlle" +
                            "rs", typeof(SubmissionsControllers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extention..
        /// </summary>
        public static string Invalid_file_extention {
            get {
                return ResourceManager.GetString("Invalid_file_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid submission!.
        /// </summary>
        public static string Invalid_submission_message {
            get {
                return ResourceManager.GetString("Invalid_submission_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem is not for the same contest as the choosen participant..
        /// </summary>
        public static string Invalid_task_for_participant {
            get {
                return ResourceManager.GetString("Invalid_task_for_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission retest started!.
        /// </summary>
        public static string Retest_successful {
            get {
                return ResourceManager.GetString("Retest_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is over the size limit!.
        /// </summary>
        public static string Submission_content_length_invalid {
            get {
                return ResourceManager.GetString("Submission_content_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission is being processed and cannot be retested right now!.
        /// </summary>
        public static string Submission_is_processing {
            get {
                return ResourceManager.GetString("Submission_is_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission added successfully!.
        /// </summary>
        public static string Successful_creation_message {
            get {
                return ResourceManager.GetString("Successful_creation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission eddited successfully!.
        /// </summary>
        public static string Successful_edit_message {
            get {
                return ResourceManager.GetString("Successful_edit_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong submission type!.
        /// </summary>
        public static string Wrong_submision_type {
            get {
                return ResourceManager.GetString("Wrong_submision_type", resourceCulture);
            }
        }
    }
}
