//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Account.ViewModels.AccountViewModels", typeof(AccountViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already been registered.
        /// </summary>
        public static string Email_already_registered {
            get {
                return ResourceManager.GetString("Email_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        public static string Email_confirm {
            get {
                return ResourceManager.GetString("Email_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double check the email address that you entered.
        /// </summary>
        public static string Email_confirmation_invalid {
            get {
                return ResourceManager.GetString("Email_confirmation_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email.
        /// </summary>
        public static string Email_confirmation_required {
            get {
                return ResourceManager.GetString("Email_confirmation_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Email_invalid {
            get {
                return ResourceManager.GetString("Email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        public static string Email_required {
            get {
                return ResourceManager.GetString("Email_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password.
        /// </summary>
        public static string Enter_new_password_confirmation {
            get {
                return ResourceManager.GetString("Enter_new_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        public static string Enter_new_password_validation {
            get {
                return ResourceManager.GetString("Enter_new_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string Enter_password {
            get {
                return ResourceManager.GetString("Enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        public static string Enter_password_validation {
            get {
                return ResourceManager.GetString("Enter_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match.
        /// </summary>
        public static string New_password_confirm_password_not_matching_validation {
            get {
                return ResourceManager.GetString("New_password_confirm_password_not_matching_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string New_password_confirmation {
            get {
                return ResourceManager.GetString("New_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string Password_confirm {
            get {
                return ResourceManager.GetString("Password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string Password_incorrect {
            get {
                return ResourceManager.GetString("Password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least {2} characters long..
        /// </summary>
        public static string Password_length_validation_message {
            get {
                return ResourceManager.GetString("Password_length_validation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string Password_required {
            get {
                return ResourceManager.GetString("Password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords don&apos;t match.
        /// </summary>
        public static string Passwords_dont_match {
            get {
                return ResourceManager.GetString("Passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is not available.
        /// </summary>
        public static string User_already_registered {
            get {
                return ResourceManager.GetString("User_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the new username.
        /// </summary>
        public static string Username_confirmation {
            get {
                return ResourceManager.GetString("Username_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The usernames do not match.
        /// </summary>
        public static string Username_confirmation_incorrect {
            get {
                return ResourceManager.GetString("Username_confirmation_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can contain only latin characters, numbers and the symbols &apos;.&apos; or &apos;_&apos;. The username must start with a letter and end with a letter or number..
        /// </summary>
        public static string Username_regex_validation {
            get {
                return ResourceManager.GetString("Username_regex_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string Username_required {
            get {
                return ResourceManager.GetString("Username_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be between {2} and {1} characters long.
        /// </summary>
        public static string Username_validation {
            get {
                return ResourceManager.GetString("Username_validation", resourceCulture);
            }
        }
    }
}
