//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Participants.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParticipantViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParticipantViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Participants.ViewModels.Particip" +
                            "antViewModels", typeof(ParticipantViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer is required!.
        /// </summary>
        public static string Answer_required {
            get {
                return ResourceManager.GetString("Answer_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest_name {
            get {
                return ResourceManager.GetString("Contest_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contest is required!.
        /// </summary>
        public static string Contest_required {
            get {
                return ResourceManager.GetString("Contest_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is offical?.
        /// </summary>
        public static string Is_official {
            get {
                return ResourceManager.GetString("Is_official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation end.
        /// </summary>
        public static string Participation_end_time {
            get {
                return ResourceManager.GetString("Participation_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation start.
        /// </summary>
        public static string Participation_start_time {
            get {
                return ResourceManager.GetString("Participation_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is required!.
        /// </summary>
        public static string User_required {
            get {
                return ResourceManager.GetString("User_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
