//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.AntiCheat.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AntiCheatViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntiCheatViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.AntiCheat.Views.AntiCheatViews", typeof(AntiCheatViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By IP.
        /// </summary>
        public static string By_ip_page_title {
            get {
                return ResourceManager.GetString("By_ip_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By submission similarity.
        /// </summary>
        public static string By_submission_page_title {
            get {
                return ResourceManager.GetString("By_submission_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose or enter contest....
        /// </summary>
        public static string Choose_or_enter_contest {
            get {
                return ResourceManager.GetString("Choose_or_enter_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differences.
        /// </summary>
        public static string Differences {
            get {
                return ResourceManager.GetString("Differences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Participant.
        /// </summary>
        public static string First_participant {
            get {
                return ResourceManager.GetString("First_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Addresses.
        /// </summary>
        public static string Ip_addresses {
            get {
                return ResourceManager.GetString("Ip_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Id.
        /// </summary>
        public static string Participant_id {
            get {
                return ResourceManager.GetString("Participant_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Participant.
        /// </summary>
        public static string Second_participant {
            get {
                return ResourceManager.GetString("Second_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
