//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.Views.Contests.ContestsDetails", typeof(ContestsDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed languages.
        /// </summary>
        public static string Allowed_languages {
            get {
                return ResourceManager.GetString("Allowed_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change time.
        /// </summary>
        public static string Change_time {
            get {
                return ResourceManager.GetString("Change_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compete.
        /// </summary>
        public static string Compete {
            get {
                return ResourceManager.GetString("Compete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contest is active until.
        /// </summary>
        public static string Competition_active_until {
            get {
                return ResourceManager.GetString("Competition_active_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest details.
        /// </summary>
        public static string Contest_details {
            get {
                return ResourceManager.GetString("Contest_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest full results.
        /// </summary>
        public static string Contest_full_results {
            get {
                return ResourceManager.GetString("Contest_full_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest participants.
        /// </summary>
        public static string Contest_participants {
            get {
                return ResourceManager.GetString("Contest_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest results.
        /// </summary>
        public static string Contest_results {
            get {
                return ResourceManager.GetString("Contest_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string Contests {
            get {
                return ResourceManager.GetString("Contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full results.
        /// </summary>
        public static string Full_results {
            get {
                return ResourceManager.GetString("Full_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no description for the selected contest..
        /// </summary>
        public static string No_contest_description {
            get {
                return ResourceManager.GetString("No_contest_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practicing is allowed until.
        /// </summary>
        public static string Practice_active_until {
            get {
                return ResourceManager.GetString("Practice_active_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice full results.
        /// </summary>
        public static string Practice_full_results {
            get {
                return ResourceManager.GetString("Practice_full_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice participants.
        /// </summary>
        public static string Practice_participants {
            get {
                return ResourceManager.GetString("Practice_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice results.
        /// </summary>
        public static string Practice_results {
            get {
                return ResourceManager.GetString("Practice_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem groups.
        /// </summary>
        public static string Problem_groups {
            get {
                return ResourceManager.GetString("Problem_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problems for this contest are not public..
        /// </summary>
        public static string Problems_are_not_public {
            get {
                return ResourceManager.GetString("Problems_are_not_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
    }
}
