// <auto-generated />
namespace OJS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoveContestSubmissionTypesAndAddJavaUnitTestingAndCPlusPlusZipStrategies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveContestSubmissionTypesAndAddJavaUnitTestingAndCPlusPlusZipStrategies));
        
        string IMigrationMetadata.Id
        {
            get { return "201704101836345_RemoveContestSubmissionTypesAndAddJavaUnitTestingAndCPlusPlusZipStrategies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
