// <auto-generated />
namespace OJS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class identity_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identity_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220830272_identity_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
