//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Base {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Base.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not set a password for your profile. Please set your password using &lt;a href=&quot;/Account/Manage&quot;&gt;this link&lt;/a&gt;..
        /// </summary>
        public static string Password_not_set {
            get {
                return ResourceManager.GetString("Password_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username contains symbols that are not allowed, is shorter than 5 characters or is longer than 15 characters. You can change it using &lt;a href=&quot;/Account/ChangeUsername&quot;&gt;this link&lt;/a&gt;..
        /// </summary>
        public static string Username_in_invalid_format {
            get {
                return ResourceManager.GetString("Username_in_invalid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the new version of the BGCoder.com system!&lt;br /&gt;All data (except user passwords) were transferred from the old version of the system to the new one.&lt;br /&gt;If you had an account in the old system you should use the &quot;&lt;a href=&quot;/Account/ForgottenPassword&quot;&gt;forgotten password&lt;/a&gt;&quot; link to activate your account in the new system..
        /// </summary>
        public static string Welcome_to_the_new_bgcoder_and_change_password {
            get {
                return ResourceManager.GetString("Welcome_to_the_new_bgcoder_and_change_password", resourceCulture);
            }
        }
    }
}
