//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Users.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Users.ViewModels.ProfileViewModels", typeof(ProfileViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city must be less than {1} characters long.
        /// </summary>
        public static string City_too_long {
            get {
                return ResourceManager.GetString("City_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name must be less than {1} characters long.
        /// </summary>
        public static string Company_too_long {
            get {
                return ResourceManager.GetString("Company_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education institution.
        /// </summary>
        public static string Education_institution {
            get {
                return ResourceManager.GetString("Education_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The education institution must be less than {1} characters long.
        /// </summary>
        public static string Education_too_long {
            get {
                return ResourceManager.GetString("Education_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty number.
        /// </summary>
        public static string Faculty_number {
            get {
                return ResourceManager.GetString("Faculty_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The faculty number must be less than {1} characters long.
        /// </summary>
        public static string Faculty_number_too_long {
            get {
                return ResourceManager.GetString("Faculty_number_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family_name {
            get {
                return ResourceManager.GetString("Family_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family name must be less than {1} characters long.
        /// </summary>
        public static string Family_name_too_long {
            get {
                return ResourceManager.GetString("Family_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name must be less than {1} characters long.
        /// </summary>
        public static string First_name_too_long {
            get {
                return ResourceManager.GetString("First_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string Job_title {
            get {
                return ResourceManager.GetString("Job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job title must be less than {1} characters long.
        /// </summary>
        public static string Job_title_too_long {
            get {
                return ResourceManager.GetString("Job_title_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string No_information {
            get {
                return ResourceManager.GetString("No_information", resourceCulture);
            }
        }
    }
}
