//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.ContestsGeneral", typeof(ContestsGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission type does not allow sending binary files.
        /// </summary>
        public static string Binary_files_not_allowed {
            get {
                return ResourceManager.GetString("Binary_files_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category does not exist!.
        /// </summary>
        public static string Category_not_found {
            get {
                return ResourceManager.GetString("Category_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compete.
        /// </summary>
        public static string Compete {
            get {
                return ResourceManager.GetString("Compete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contest cannot be competed!.
        /// </summary>
        public static string Contest_cannot_be_competed {
            get {
                return ResourceManager.GetString("Contest_cannot_be_competed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contest cannot be practiced!.
        /// </summary>
        public static string Contest_cannot_be_practiced {
            get {
                return ResourceManager.GetString("Contest_cannot_be_practiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contest id was provided!.
        /// </summary>
        public static string Contest_not_found {
            get {
                return ResourceManager.GetString("Contest_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contest results are not available!.
        /// </summary>
        public static string Contest_results_not_available {
            get {
                return ResourceManager.GetString("Contest_results_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension.
        /// </summary>
        public static string Invalid_extention {
            get {
                return ResourceManager.GetString("Invalid_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request!.
        /// </summary>
        public static string Invalid_request {
            get {
                return ResourceManager.GetString("Invalid_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        public static string Invalid_selection {
            get {
                return ResourceManager.GetString("Invalid_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main categories.
        /// </summary>
        public static string Main_categories {
            get {
                return ResourceManager.GetString("Main_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem is not part of your problems for the exam.
        /// </summary>
        public static string Problem_not_assigned_to_user {
            get {
                return ResourceManager.GetString("Problem_not_assigned_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem was not found!.
        /// </summary>
        public static string Problem_not_found {
            get {
                return ResourceManager.GetString("Problem_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot view the results for this problem!.
        /// </summary>
        public static string Problem_results_not_available {
            get {
                return ResourceManager.GetString("Problem_results_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking for {0} {1}.xls.
        /// </summary>
        public static string Report_excel_format {
            get {
                return ResourceManager.GetString("Report_excel_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource cannot be downloaded!.
        /// </summary>
        public static string Resource_cannot_be_downloaded {
            get {
                return ResourceManager.GetString("Resource_cannot_be_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution uploaded..
        /// </summary>
        public static string Solution_uploaded {
            get {
                return ResourceManager.GetString("Solution_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid submission requested!.
        /// </summary>
        public static string Submission_not_found {
            get {
                return ResourceManager.GetString("Submission_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission was not made by you!.
        /// </summary>
        public static string Submission_not_made_by_user {
            get {
                return ResourceManager.GetString("Submission_not_made_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submitted code is too long!.
        /// </summary>
        public static string Submission_too_long {
            get {
                return ResourceManager.GetString("Submission_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong submission type!.
        /// </summary>
        public static string Submission_type_not_found {
            get {
                return ResourceManager.GetString("Submission_type_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission was sent too soon!.
        /// </summary>
        public static string Submission_was_sent_too_soon {
            get {
                return ResourceManager.GetString("Submission_was_sent_too_soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This submission type does not allow sending text.
        /// </summary>
        public static string Text_upload_not_allowed {
            get {
                return ResourceManager.GetString("Text_upload_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file..
        /// </summary>
        public static string Upload_file {
            get {
                return ResourceManager.GetString("Upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unprocessed submission for this problem. Please wait until the submission is processed..
        /// </summary>
        public static string User_has_not_processed_submission_for_problem {
            get {
                return ResourceManager.GetString("User_has_not_processed_submission_for_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered for this exam!.
        /// </summary>
        public static string User_is_not_registered_for_exam {
            get {
                return ResourceManager.GetString("User_is_not_registered_for_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
