//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Users.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfileAdministration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfileAdministration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Users.ViewModels.UserProfileAdmi" +
                            "nistration", typeof(UserProfileAdministration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered city is too long.
        /// </summary>
        public static string City_length {
            get {
                return ResourceManager.GetString("City_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered company name is too long.
        /// </summary>
        public static string Company_length {
            get {
                return ResourceManager.GetString("Company_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational institution.
        /// </summary>
        public static string Educational_institution {
            get {
                return ResourceManager.GetString("Educational_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The educational institution name is too long.
        /// </summary>
        public static string Educational_institution_length {
            get {
                return ResourceManager.GetString("Educational_institution_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty number.
        /// </summary>
        public static string Faculty_number {
            get {
                return ResourceManager.GetString("Faculty_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered faculty number is too long.
        /// </summary>
        public static string Faculty_number_length {
            get {
                return ResourceManager.GetString("Faculty_number_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered name is too long.
        /// </summary>
        public static string First_name_length {
            get {
                return ResourceManager.GetString("First_name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string Job_title {
            get {
                return ResourceManager.GetString("Job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered job title name is too long.
        /// </summary>
        public static string Job_title_length {
            get {
                return ResourceManager.GetString("Job_title_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered last name is too long.
        /// </summary>
        public static string Last_name_length {
            get {
                return ResourceManager.GetString("Last_name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Mail_invalid {
            get {
                return ResourceManager.GetString("Mail_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is too long!.
        /// </summary>
        public static string Mail_length {
            get {
                return ResourceManager.GetString("Mail_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required!.
        /// </summary>
        public static string Mail_required {
            get {
                return ResourceManager.GetString("Mail_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string Null_display_text {
            get {
                return ResourceManager.GetString("Null_display_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required!.
        /// </summary>
        public static string Username_required {
            get {
                return ResourceManager.GetString("Username_required", resourceCulture);
            }
        }
    }
}
