//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestsControllers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsControllers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Tests.TestsControllers", typeof(TestsControllers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid problem.
        /// </summary>
        public static string Invalid_problem {
            get {
                return ResourceManager.GetString("Invalid_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid test.
        /// </summary>
        public static string Invalid_test {
            get {
                return ResourceManager.GetString("Invalid_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tests.
        /// </summary>
        public static string Invalid_tests {
            get {
                return ResourceManager.GetString("Invalid_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be a zip.
        /// </summary>
        public static string Must_be_zip {
            get {
                return ResourceManager.GetString("Must_be_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must not be empty.
        /// </summary>
        public static string No_empty_file {
            get {
                return ResourceManager.GetString("No_empty_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem does not exist.
        /// </summary>
        public static string Problem_does_not_exist {
            get {
                return ResourceManager.GetString("Problem_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test added successfully..
        /// </summary>
        public static string Test_added_successfully {
            get {
                return ResourceManager.GetString("Test_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test deleted successfully..
        /// </summary>
        public static string Test_deleted_successfully {
            get {
                return ResourceManager.GetString("Test_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test edited successfully.
        /// </summary>
        public static string Test_edited_successfully {
            get {
                return ResourceManager.GetString("Test_edited_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tests added to problem successfully..
        /// </summary>
        public static string Tests_added_to_problem {
            get {
                return ResourceManager.GetString("Tests_added_to_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests deleted successfully..
        /// </summary>
        public static string Tests_deleted_successfully {
            get {
                return ResourceManager.GetString("Tests_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip is damaged.
        /// </summary>
        public static string Zip_damaged {
            get {
                return ResourceManager.GetString("Zip_damaged", resourceCulture);
            }
        }
    }
}
