//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.SubmissionTypes.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionTypeAdministration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionTypeAdministration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.SubmissionTypes.ViewModels.Submi" +
                            "ssionTypeAdministration", typeof(SubmissionTypeAdministration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional compiler arguments.
        /// </summary>
        public static string Additional_compiler_arguments {
            get {
                return ResourceManager.GetString("Additional_compiler_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow binary files upload.
        /// </summary>
        public static string Allow_binary_files_upload {
            get {
                return ResourceManager.GetString("Allow_binary_files_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file extensions.
        /// </summary>
        public static string Allowed_file_extensions {
            get {
                return ResourceManager.GetString("Allowed_file_extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        public static string Compiler_type {
            get {
                return ResourceManager.GetString("Compiler_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution strategy.
        /// </summary>
        public static string Execution_strategy_type {
            get {
                return ResourceManager.GetString("Execution_strategy_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is selected?.
        /// </summary>
        public static string Is_selected {
            get {
                return ResourceManager.GetString("Is_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted length is between {2} and {1} symbols.
        /// </summary>
        public static string Name_length {
            get {
                return ResourceManager.GetString("Name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required!.
        /// </summary>
        public static string Name_required {
            get {
                return ResourceManager.GetString("Name_required", resourceCulture);
            }
        }
    }
}
