//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests.Views.Partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.Views.Partials.ContestE" +
                            "ditor", typeof(ContestEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to automatically determine test detailed feedback visibility depending on contest type (practice/compete).
        /// </summary>
        public static string Auto_change_tests {
            get {
                return ResourceManager.GetString("Auto_change_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category of the contest.
        /// </summary>
        public static string Choose_category {
            get {
                return ResourceManager.GetString("Choose_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contest end time.
        /// </summary>
        public static string Contest_end {
            get {
                return ResourceManager.GetString("Contest_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the contest order.
        /// </summary>
        public static string Contest_order {
            get {
                return ResourceManager.GetString("Contest_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contest password.
        /// </summary>
        public static string Contest_password {
            get {
                return ResourceManager.GetString("Contest_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contest start time.
        /// </summary>
        public static string Contest_start {
            get {
                return ResourceManager.GetString("Contest_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose if the contest is visible.
        /// </summary>
        public static string Contest_visibility {
            get {
                return ResourceManager.GetString("Contest_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the duration of the exam in hours.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration information.
        /// </summary>
        public static string Duration_info {
            get {
                return ResourceManager.GetString("Duration_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of the contest.
        /// </summary>
        public static string Enter_description {
            get {
                return ResourceManager.GetString("Enter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title of the contest.
        /// </summary>
        public static string Enter_title {
            get {
                return ResourceManager.GetString("Enter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the count of the problem groups for online contest.
        /// </summary>
        public static string Number_of_problem_groups {
            get {
                return ResourceManager.GetString("Number_of_problem_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        public static string Passowords_info {
            get {
                return ResourceManager.GetString("Passowords_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter practice end time.
        /// </summary>
        public static string Practice_end {
            get {
                return ResourceManager.GetString("Practice_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter practice password.
        /// </summary>
        public static string Practice_password {
            get {
                return ResourceManager.GetString("Practice_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter practice start time.
        /// </summary>
        public static string Practice_start {
            get {
                return ResourceManager.GetString("Practice_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage problem groups count from the Problem Groups Administration.
        /// </summary>
        public static string Problem_groups_edit_from_administration {
            get {
                return ResourceManager.GetString("Problem_groups_edit_from_administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission types.
        /// </summary>
        public static string Submission_types {
            get {
                return ResourceManager.GetString("Submission_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a time limit between two consecutive submissions.
        /// </summary>
        public static string Submissions_limit {
            get {
                return ResourceManager.GetString("Submissions_limit", resourceCulture);
            }
        }
    }
}
