//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJS.Tools.OldDatabaseMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public int Id { get; set; }
        public Nullable<int> User { get; set; }
        public int Contest { get; set; }
        public string Answer { get; set; }
        public bool IsOfficial { get; set; }
        public int TotalPoints { get; set; }
        public System.DateTime RegisteredOn { get; set; }
    
        public virtual User User1 { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
