//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJS.Tools.OldDatabaseMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Submissions = new HashSet<Submission>();
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public int Contest { get; set; }
        public string Name { get; set; }
        public byte[] Description { get; set; }
        public string DescriptionFormat { get; set; }
        public string DescriptionLink { get; set; }
        public int MaxPoints { get; set; }
        public bool RequiresAllTests { get; set; }
        public int TimeLimit { get; set; }
        public long MemoryLimit { get; set; }
        public bool RequiresZeroTests { get; set; }
        public int Checker { get; set; }
        public bool JudgeNow { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual Checker Checker1 { get; set; }
        public virtual Contest Contest1 { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
