//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJS.Tools.OldDatabaseMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Id { get; set; }
        public int Task { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
        public bool IsZeroTest { get; set; }
        public int Order { get; set; }
    
        public virtual Task Task1 { get; set; }
    }
}
