//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Home.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Home.Views.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active contests.
        /// </summary>
        public static string Active_contests {
            get {
                return ResourceManager.GetString("Active_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest categories.
        /// </summary>
        public static string Contest_categories {
            get {
                return ResourceManager.GetString("Contest_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines for working with the Judge system.
        /// </summary>
        public static string Guidelines_link_title {
            get {
                return ResourceManager.GetString("Guidelines_link_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infinite.
        /// </summary>
        public static string Infinite {
            get {
                return ResourceManager.GetString("Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there are no active contests..
        /// </summary>
        public static string No_active_contests {
            get {
                return ResourceManager.GetString("No_active_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous contests.
        /// </summary>
        public static string No_previous_contests {
            get {
                return ResourceManager.GetString("No_previous_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate.
        /// </summary>
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous contests.
        /// </summary>
        public static string Previous_contests {
            get {
                return ResourceManager.GetString("Previous_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftUni Judge.
        /// </summary>
        public static string Project_title {
            get {
                return ResourceManager.GetString("Project_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining.
        /// </summary>
        public static string Remaining_time {
            get {
                return ResourceManager.GetString("Remaining_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
