//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Common.Resources.Enums.EnumTranslations", typeof(EnumTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors Solution.
        /// </summary>
        public static string AuthorsSolution {
            get {
                return ResourceManager.GetString("AuthorsSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDown.
        /// </summary>
        public static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded from homework.
        /// </summary>
        public static string Excluded_from_homework_problem_group {
            get {
                return ResourceManager.GetString("Excluded_from_homework_problem_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLine TextBox.
        /// </summary>
        public static string MultiLineTextBox {
            get {
                return ResourceManager.GetString("MultiLineTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Practical Exam.
        /// </summary>
        public static string Online_practical_exam {
            get {
                return ResourceManager.GetString("Online_practical_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onsite Practical Exam.
        /// </summary>
        public static string Onsite_practical_exam {
            get {
                return ResourceManager.GetString("Onsite_practical_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenTestDescription {
            get {
                return ResourceManager.GetString("OpenTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PendingSubmissionStatus {
            get {
                return ResourceManager.GetString("PendingSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Description.
        /// </summary>
        public static string ProblemDescription {
            get {
                return ResourceManager.GetString("ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string ProcessedSubmissionStatus {
            get {
                return ResourceManager.GetString("ProcessedSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string StandardTestDescription {
            get {
                return ResourceManager.GetString("StandardTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string TrialTestDescription {
            get {
                return ResourceManager.GetString("TrialTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
