//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestAdministration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestAdministration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.ViewModels.ContestAdmin" +
                            "istration", typeof(ContestAdministration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically change test detailed feedback visiblity.
        /// </summary>
        public static string Auto_change_tests_feedback_visibility {
            get {
                return ResourceManager.GetString("Auto_change_tests_feedback_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_name {
            get {
                return ResourceManager.GetString("Category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is required!.
        /// </summary>
        public static string Category_required {
            get {
                return ResourceManager.GetString("Category_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest password.
        /// </summary>
        public static string Contest_password {
            get {
                return ResourceManager.GetString("Contest_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End_time {
            get {
                return ResourceManager.GetString("End_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted length for the name is between {2} and {1} symbols.
        /// </summary>
        public static string Name_length {
            get {
                return ResourceManager.GetString("Name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required!.
        /// </summary>
        public static string Name_required {
            get {
                return ResourceManager.GetString("Name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem groups count.
        /// </summary>
        public static string Number_of_problem_groups {
            get {
                return ResourceManager.GetString("Number_of_problem_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is required!.
        /// </summary>
        public static string Order_required {
            get {
                return ResourceManager.GetString("Order_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password cannot be longer than {1} symbols.
        /// </summary>
        public static string Password_max_length {
            get {
                return ResourceManager.GetString("Password_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice end.
        /// </summary>
        public static string Practice_end_time {
            get {
                return ResourceManager.GetString("Practice_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice password.
        /// </summary>
        public static string Practice_password {
            get {
                return ResourceManager.GetString("Practice_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice start.
        /// </summary>
        public static string Practice_start_time {
            get {
                return ResourceManager.GetString("Practice_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start_time {
            get {
                return ResourceManager.GetString("Start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submision types.
        /// </summary>
        public static string Submision_types {
            get {
                return ResourceManager.GetString("Submision_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between submissions.
        /// </summary>
        public static string Submissions_limit {
            get {
                return ResourceManager.GetString("Submissions_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is visible?.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
