//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompeteRegister {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompeteRegister() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.Views.Compete.CompeteRegister", typeof(CompeteRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the contest now?.
        /// </summary>
        public static string Are_you_sure_start_online_contest {
            get {
                return ResourceManager.GetString("Are_you_sure_start_online_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time will start counting down when you press the &quot;{0}&quot; button.&lt;br /&gt;&lt;br /&gt;
        ///In the case of unexpected problems (turning off your computer, exiting the page/system, internet connection failure), &lt;strong&gt;the time lost will not be restored&lt;/strong&gt;. When your time runs out, you &lt;strong&gt;will not&lt;/strong&gt; be able to compete in this competition again.&lt;br /&gt;&lt;br /&gt;
        ///When you click the &quot;{0}&quot; button &lt;strong&gt;{1} random problems, one of each type, will be generated&lt;/strong&gt; for you..
        /// </summary>
        public static string Confirm_online_contest_information {
            get {
                return ResourceManager.GetString("Confirm_online_contest_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting now &lt;strong&gt;you will have {0} hours&lt;/strong&gt; to complete the contest &lt;strong&gt;{1}&lt;/strong&gt;..
        /// </summary>
        public static string Confirm_online_contest_start_message {
            get {
                return ResourceManager.GetString("Confirm_online_contest_start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string Empty_Password {
            get {
                return ResourceManager.GetString("Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all questions.
        /// </summary>
        public static string Not_all_questions_answered {
            get {
                return ResourceManager.GetString("Not_all_questions_answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an answer.
        /// </summary>
        public static string Select_dropdown_answer {
            get {
                return ResourceManager.GetString("Select_dropdown_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
    }
}
