//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsProblemPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsProblemPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.Shared.ContestsProblemPartial", typeof(ContestsProblemPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed memory.
        /// </summary>
        public static string Allowed_memory {
            get {
                return ResourceManager.GetString("Allowed_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed working time.
        /// </summary>
        public static string Allowed_working_time {
            get {
                return ResourceManager.GetString("Allowed_working_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system does not make difference between small and capital letters when comparing the sent code result with the expected output symbol by symbol.
        /// </summary>
        public static string Case_insensitive_checker_description {
            get {
                return ResourceManager.GetString("Case_insensitive_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change_admin_button {
            get {
                return ResourceManager.GetString("Change_admin_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker types:.
        /// </summary>
        public static string Checker_types {
            get {
                return ResourceManager.GetString("Checker_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile time error.
        /// </summary>
        public static string Compile_time_error {
            get {
                return ResourceManager.GetString("Compile_time_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled successfully.
        /// </summary>
        public static string Compiled_successfully {
            get {
                return ResourceManager.GetString("Compiled_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_admin_button {
            get {
                return ResourceManager.GetString("Delete_admin_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - the system compares the sent code result with the expected output symbol by symbol.
        /// </summary>
        public static string Exact_checker_description {
            get {
                return ResourceManager.GetString("Exact_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not included in final score.
        /// </summary>
        public static string Not_included_in_final_score {
            get {
                return ResourceManager.GetString("Not_included_in_final_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not processed yet.
        /// </summary>
        public static string Not_processed {
            get {
                return ResourceManager.GetString("Not_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants_admin_button {
            get {
                return ResourceManager.GetString("Participants_admin_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - only for tasks with end result decimal number - the system compares only the first N digits after the decimal point.
        /// </summary>
        public static string Precision_checker_description {
            get {
                return ResourceManager.GetString("Precision_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem results.
        /// </summary>
        public static string Problem_results {
            get {
                return ResourceManager.GetString("Problem_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system sorts all lines in the sent code result and then compares symbol by symbol with the expected output.
        /// </summary>
        public static string Sort_checker_description {
            get {
                return ResourceManager.GetString("Sort_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissions.
        /// </summary>
        public static string Submissions {
            get {
                return ResourceManager.GetString("Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests_admin_button {
            get {
                return ResourceManager.GetString("Tests_admin_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and memory used.
        /// </summary>
        public static string Time_and_memory {
            get {
                return ResourceManager.GetString("Time_and_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system trims the whitespace before and after the sent code result and then compares symbol by symbol with the expected output.
        /// </summary>
        public static string Trim_checker_description {
            get {
                return ResourceManager.GetString("Trim_checker_description", resourceCulture);
            }
        }
    }
}
