//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Problems.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProblemsEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProblemsEdit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Problems.Views.ProblemsEdit", typeof(ProblemsEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove resource for this problem - problem description, solution or video. Every resource has a name, type and a file/llink..
        /// </summary>
        public static string Add_remove_resource {
            get {
                return ResourceManager.GetString("Add_remove_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system does uses case insensitive comparison when comparing symbol by symbol..
        /// </summary>
        public static string Case_insensitive_checker_description {
            get {
                return ResourceManager.GetString("Case_insensitive_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a source code checker for this problem. The basic options are:.
        /// </summary>
        public static string Choose_code_checker {
            get {
                return ResourceManager.GetString("Choose_code_checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Choose_file {
            get {
                return ResourceManager.GetString("Choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the .zip file with expected input and output for the current problem.
        ///    &lt;br /&gt;
        ///    You can download a sample zip file from
        ///    &lt;a href=&quot;/Content/Demos/DemoTests.zip&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string Choose_zip_file {
            get {
                return ResourceManager.GetString("Choose_zip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the max points for the problem.
        /// </summary>
        public static string Enter_max_points {
            get {
                return ResourceManager.GetString("Enter_max_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the memory limit (in bytes) for this problem.
        /// </summary>
        public static string Enter_memory_limit {
            get {
                return ResourceManager.GetString("Enter_memory_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the problem.
        /// </summary>
        public static string Enter_name {
            get {
                return ResourceManager.GetString("Enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the order for the current problem.
        /// </summary>
        public static string Enter_order {
            get {
                return ResourceManager.GetString("Enter_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the source code size limit (in bytes) for this problem.
        /// </summary>
        public static string Enter_sorce_code_size_limit {
            get {
                return ResourceManager.GetString("Enter_sorce_code_size_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the time limit (in miliseconds) for this problem.
        /// </summary>
        public static string Enter_time_limit {
            get {
                return ResourceManager.GetString("Enter_time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system compares the results of the participants with the expected output symbol by symbol..
        /// </summary>
        public static string Exact_checker_description {
            get {
                return ResourceManager.GetString("Exact_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create problem.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system compares only N digits after the decimal separator. Works only for problems where the answers are floating point numbers positioned on new lines..
        /// </summary>
        public static string Precision_checker_description {
            get {
                return ResourceManager.GetString("Precision_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose if the participants can see a full feedback for thier submissions (like administrators).
        /// </summary>
        public static string Show_detailed_feedback {
            get {
                return ResourceManager.GetString("Show_detailed_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose if the participants can see their result in real time.
        /// </summary>
        public static string Show_results {
            get {
                return ResourceManager.GetString("Show_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system first sorts the results of the participants and the expected output, line by line and  then compares them both symbol by symbol..
        /// </summary>
        public static string Sort_checker_description {
            get {
                return ResourceManager.GetString("Sort_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests (.zip file).
        /// </summary>
        public static string Tests_label {
            get {
                return ResourceManager.GetString("Tests_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - the system first removes the white spaces in front and in the end of the participant results and then compare them with the expected output symbol by symbol..
        /// </summary>
        public static string Trim_checker_description {
            get {
                return ResourceManager.GetString("Trim_checker_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
