//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Tests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestsIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Tests.Views.TestsIndex", typeof(TestsIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string Category_label {
            get {
                return ResourceManager.GetString("Category_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category....
        /// </summary>
        public static string Choose_category {
            get {
                return ResourceManager.GetString("Choose_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose contest....
        /// </summary>
        public static string Choose_contest {
            get {
                return ResourceManager.GetString("Choose_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose problem....
        /// </summary>
        public static string Choose_problem {
            get {
                return ResourceManager.GetString("Choose_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest:.
        /// </summary>
        public static string Contest_label {
            get {
                return ResourceManager.GetString("Contest_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old tests.
        /// </summary>
        public static string Delete_old_tests {
            get {
                return ResourceManager.GetString("Delete_old_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter problem....
        /// </summary>
        public static string Enter_problem {
            get {
                return ResourceManager.GetString("Enter_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Page_title {
            get {
                return ResourceManager.GetString("Page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem:.
        /// </summary>
        public static string Problem_label {
            get {
                return ResourceManager.GetString("Problem_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest problem.
        /// </summary>
        public static string Retest_problem {
            get {
                return ResourceManager.GetString("Retest_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by problem:.
        /// </summary>
        public static string Search_by_problem {
            get {
                return ResourceManager.GetString("Search_by_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests loading....
        /// </summary>
        public static string Tests_loading {
            get {
                return ResourceManager.GetString("Tests_loading", resourceCulture);
            }
        }
    }
}
